application: nvsl-progress-reports
version: testing
runtime: python27
api_version: 1
threadsafe: yes

handlers:


- url: /static
  static_dir: static

- url: /?
  script: server.smithers.app
  login: required

#- url: /app/enforce_deadlines
#  script: server.locutor.app
#  login: admin
- url: /whitelist
  script: server.smithers.app
  login: admin

- url: /student.*
  script: server.smithers.app
  login: admin

- url: /.*
  script: server.smithers.app
  login: required

- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

env_variables:
#  CLOUDSDK_CONFIG: "/Users/swanson/.config/gcloud/configurations/config_nvslapply"
  FLASK_DEBUG: 1

libraries:
- name: webapp2
  version: "2.5.2"
- name: lxml
  version: latest
- name: jinja2
  version: latest
#- name: pycrypto
#  version: latest

skip_files:
- server/local_mode.flag


